### PR TITLE
Lunchbox Crash Prevention

### LINKED ISSUE #23239: Lunchbox NEI Crash
### Your GTNH Discord Username

eridanisys

### Your Pack Version

2.8.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

when accessing NEI menus in the lunchbox inventory, I experienced a world crash.
specific steps: while holding lunchbox, right click to access its inventory -> add garlic (harvestcraft:garlicItem) to the lunchbox -> press R on lunchbox to view recipe -> press esc to close recipe viewer -> closing internal server -> better crash screen

### Crash Report

https://mclo.gs/IRVbltz

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

### PR DESCRIPTION
**Pull request by UltraProdigy**
This fixes a crash that could occur when closing Lunchbox GUI at the same time as another GUI like NEI or when closing lunchbox and inventory. I think during resync, the ItemStack becomes temporarily null & hence the UUID from that stack, causing an NPE.

This just caches the UUID and adds a bunch of null protection as well as a few IntelliJ suggestions because who am I to argue with IDE authority.

Tested in fullpack. Works.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/23239

### CODE REVIEW

File: src/main/java/squeek/spiceoflife/items/ItemFoodContainer.java [hunk 1]
```diff
@@ -132,7 +147,9 @@ public boolean isItemValidForSlot(NBTInventory inventory, int slotNum, ItemStack
     }
 
     public void setIsOpen(ItemStack itemStack, boolean isOpen) {
+        if (itemStack == null) return;
         NBTTagCompound baseTag = getOrInitBaseTag(itemStack);
+        if (baseTag == null) return;
```
Comment (Nikolay-Sitnikov) [inline src/main/java/squeek/spiceoflife/items/ItemFoodContainer.java]: Only one of these two null checks is necessary.

File: src/main/java/squeek/spiceoflife/items/ItemFoodContainer.java [hunk 2]
```diff
@@ -92,13 +90,30 @@ public String getInvName(NBTInventory inventory) {
     }
 
     public UUID getUUID(ItemStack itemStack) {
-        return UUID.fromString(getOrInitBaseTag(itemStack).getString(TAG_KEY_UUID));
+        if (itemStack == null) return null;
+
+        NBTTagCompound base = getOrInitBaseTag(itemStack);
+        if (base == null) return null;
```
Comment (Ruling-0) [inline src/main/java/squeek/spiceoflife/items/ItemFoodContainer.java]: Same redundancy as previous review.
```suggestion
        NBTTagCompound base = getOrInitBaseTag(itemStack);
        if (base == null) return null;
```

Comment (UltraProdigy) [reply src/main/java/squeek/spiceoflife/items/ItemFoodContainer.java]: God how tired was I

**Review by Ruling-0 — APPROVED** [review]
